### ISSUE TITLE
启动失败，提示缺少module，但是没有详细信息

### ISSUE THREAD

**Issue by henrybit** [icepy/index-oa-template#1]
$ npm run dev

> index-oa-template@1.0.0 dev E:\code\index-oa-template.git\trunk
> node build/dev-server.js

 ERROR  Failed to compile with 1 errors10:03:24

This relative module was not found:

* ./src/main.js in multi ./build/dev-client ./src/main.js
> Listening at http://localhost:8080

**Comment by icepy** [comment]
怀疑是你那边网络不稳定，npm包没有安装完整，建议 rm -rf node_modules，重新 npm install
